version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    privileged: true
    restart: always
    user: root
    ports:
      - 18081:8080
      - 15000:50000
    container_name: jenkins-lts
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

