version: '3.1'

services:

  db:
    image: mariadb:5.5.60
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d

  adminer:
    image: adminer
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 18080:8080
